version: '3.1'

services:

  db:
    image: mysql
    container_name: sm_database
    volumes:
      - .docker/data/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306